// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../context/models.js";

/**
 * @param {string} options
 * @param {context$0.Context} ctx
 * @returns {$CancellablePromise<void>}
 */
export function ChangeWindowOptions(options, ctx) {
    return $Call.ByID(1064738860, options, ctx);
}
