// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * @param {model$0.Game} game
 * @returns {$CancellablePromise<void>}
 */
export function AddGame(game) {
    return $Call.ByID(3283329483, game);
}

/**
 * @param {model$0.Game} game
 * @returns {$CancellablePromise<void>}
 */
export function DelGame(game) {
    return $Call.ByID(943216161, game);
}

/**
 * @returns {$CancellablePromise<model$0.Game[]>}
 */
export function GetGameList() {
    return $Call.ByID(487322244).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {model$0.Game} game
 * @returns {$CancellablePromise<void>}
 */
export function UpdateGame(game) {
    return $Call.ByID(1769881985, game);
}

// Private type creation functions
const $$createType0 = model$0.Game.createFrom;
const $$createType1 = $Create.Array($$createType0);
