// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as GameService from "./gameservice.js";
import * as TaskService from "./taskservice.js";
export {
    GameService,
    TaskService
};
