// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * @param {model$0.Task} task
 * @returns {$CancellablePromise<void>}
 */
export function AddTask(task) {
    return $Call.ByID(1057964545, task);
}

/**
 * @param {model$0.Task} task
 * @returns {$CancellablePromise<void>}
 */
export function DelTask(task) {
    return $Call.ByID(2454459543, task);
}

/**
 * @param {model$0.Task} task
 * @returns {$CancellablePromise<[model$0.Task[], number]>}
 */
export function GetTaskList(task) {
    return $Call.ByID(2447123898, task).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    }));
}

/**
 * 导入任务列表
 * @param {model$0.Task} task
 * @returns {$CancellablePromise<void>}
 */
export function ImportTask(task) {
    return $Call.ByID(4085075105, task);
}

/**
 * 分享任务列表
 * @param {model$0.Task} task
 * @returns {$CancellablePromise<void>}
 */
export function ShareTask(task) {
    return $Call.ByID(65182605, task);
}

/**
 * @param {model$0.Task} task
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTask(task) {
    return $Call.ByID(4050255169, task);
}

// Private type creation functions
const $$createType0 = model$0.Task.createFrom;
const $$createType1 = $Create.Array($$createType0);
