// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Game {
    /**
     * Creates a new Game instance.
     * @param {Partial<Game>} [$$source = {}] - The source object to create the Game.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Game instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Game}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Game(/** @type {Partial<Game>} */($$parsedSource));
    }
}

/**
 * 游戏任务
 */
export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("checkDay" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["checkDay"] = 0;
        }
        if (!("isRepeat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["isRepeat"] = 0;
        }
        if (!("startDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startDate"] = "";
        }
        if (!("gameId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gameId"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}
